services:
  postgres:
    image: postgres:17
    container_name: vista_postgres
    environment:
      POSTGRES_DB: vista_pdg
      POSTGRES_USER: vista
      POSTGRES_PASSWORD: vista123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vista -d vista_pdg"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: vista_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vista.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
