spring.application.name=pdg
spring.config.import=optional:file:.env[.properties]
gemini.api.key=${GEMINI_API_KEY:change-me}
gemini.api.model=${GEMINI_API_MODEL:gemini-2.1-flash-lite}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
